version: '3.8'
services:
  db:
    image: postgres:15.7-alpine
    container_name: db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  server:
    build: server
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  gateway:
    build: gateway
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - db
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
